//
//  LicenseView.swift
//  
//
//  Created by Benedict on 05.03.22.
//

import Foundation
import SwiftUI

fileprivate let licenseText =
"""
Boost Software License - Version 1.0 - August 17th, 2003

(c) 2021/2022 Benedict St

Permission is hereby granted, free of charge, to any person or organisation
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""

struct LicenseView: View{
	@AppStorage("geozebra_hasAgreedToLicense", store: .standard) var agreedLicense: Bool = false
	@Binding var state: Int
	@State var unlockedByAgreeing = false
	@State var showLicense = false
	
	var body: some View{
		VStack(spacing: 20){
			Text("\(Image(systemName: "hand.wave.fill")) Willkommen")
				.font(.title)
				.padding(.top, 50)
			if(!showLicense){
				Text("GeoZebra | Funktionsplotter mit eigenem Computer Algebra System")
					.multilineTextAlignment(.center)
					.frame(width: 300, alignment: .center)
					.fixedSize()
				
				HStack{
					Text("GitHub:")
					Link("github.com/BenedictSt/GeoZebra \(Image(systemName: "safari"))", destination: URL(string: "https://github.com/BenedictSt/GeoZebra")!)
				}
			}
			
			//MARK: - Lizenz
			Text("\(Image(systemName: "scroll")) Lizenz")
				.font(.title2)
				.padding(.top, 20)
			
			Text("Boost Software License")
				.font(.body.italic())
			
			HStack{
				Image(systemName: "doc.on.doc").onTapGesture {copyToClipBoard(str: licenseText)}
				Text("\(Image(systemName: "c.circle")) 2022 Benedict St.").onTapGesture {showLicense.toggle()}
				Image(systemName: !showLicense ? "chevron.down.circle.fill" : "chevron.up.circle.fill").onTapGesture {showLicense.toggle()}
			}
			if(showLicense){
				ScrollView{
					Text(licenseText).multilineTextAlignment(.leading)
						.frame(width: 800, alignment: .center)
				}
				.frame(width: 900, height: 300, alignment: .center)
			}
			
			HStack{
				Button(action: {
					exit(0)
				}){
					Text("\(Image(systemName: "xmark.octagon.fill")) nicht zustimmen")
						.foregroundColor(Color(red: 0.95, green: 0, blue: 0, opacity: 1.0))
				}.buttonStyle(.borderless)
				
				Button(action: {
					showLicense = false
					unlockedByAgreeing.toggle()
				}){
					Text(!unlockedByAgreeing ? "zustimmen \(Image(systemName: "checkmark.diamond.fill"))" : "doch nicht \(Image(systemName: "arrow.uturn.backward"))")
						.foregroundColor(!unlockedByAgreeing ? Color(red: 0.08, green: 0.63, blue: 0, opacity: 1.0) : .orange)
				}.buttonStyle(.borderless)
					.keyboardShortcut("j", modifiers: [])
			}
			
			if(!showLicense){
				Image("benedictSVG")
					.resizable()
					.aspectRatio(contentMode: .fit)
					.frame(height: 50, alignment: .center)
					.padding(.top, 30)
				Spacer()
				
				HStack{
					if(!unlockedByAgreeing){Image(systemName: "lock")}
					Button(action: {
						agreedLicense = true
					}){
						Text("Starten \(Image(systemName: "chevron.right"))")
							.font(.body.bold())
					}.buttonStyle(.borderless)
				}
				.foregroundColor(unlockedByAgreeing ? .accentColor : .gray)
				.padding(.bottom, 40)
				.disabled(!unlockedByAgreeing)
			}
		}.frame(width: 1000, height: 600, alignment: .top)
	}
}
